lane :test do
  msi(
    wxs_path: 'data/SampleApp.wxs',
    fragments: {
      ApplicationData: {
        path: 'data/SampleApp/SampleApp_Data/*',
        prefix: 'data/SampleApp/',
        directory_ref: 'INSTALLDIR',
        var: 'var.SourceDir',
        component_group: 'Application.Data'
      }
    },
    defines: {
      'SourceDir' => 'data/SampleApp'
    })
end
